### 1. İşyeri Ekle
POST http://localhost:8044/isyeri/save
Content-Type: application/json

{
  "isyeriAdi": "TMO Ankara Başmüdürlüğü"
}

### 2. Depo Ekle
POST http://localhost:8044/depo/ekle
Content-Type: application/json

{
  "depoKodu": "TMO-ANK-01",
  "depoAciklama": "Ankara Merkez Silo",
  "isyeriId": 1
}

### 3. Parametre Ekle
POST http://localhost:8044/parametre/ekle
Content-Type: application/json

{
  "parametreAdi": "Sıcaklık"
}

### 4. Ürün Ekle
POST http://localhost:8044/urun/ekle
Content-Type: application/json

{
  "ad": "Buğday",
  "aciklama": "Anadolu Kırmızı Sert"
}

### 5. Referans Aralıklarını Belirle (15-25 Derece)
POST http://localhost:8044/urun/referans-ekle
Content-Type: application/json

{
  "urunId": 1,
  "parametreId": 1,
  "minDeger": 15.0,
  "maxDeger": 25.0
}

### 6. BÜYÜK FİNAL: Hatalı Ölçüm Gönder (MAİL TETİKLENECEK!)
POST http://localhost:8044/olcum/kaydet
Content-Type: application/json

{
  "depoId": 1,
  "parametreId": 1,
  "urunId": 1,
  "olcumDegeri": 30.0
}