server:
  port: 8044

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://************************** 
    username: postgres
    password: ***** 
    driver-class-name: org.postgresql.Driver
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: ozkanarda1536290@gmail.com
    password: ************* # Buraya Gmail uygulama şifreni yaz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# ARTIK EN SOLDA VE DOĞRU HİZADA
app:
  notification:
    supervisor-email: "serhanogurlu@gmail.com"